language: php

branches:
  except:
    - v0.9
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
php:
  - 7.4

matrix:
  fast_finish: true

install:
  - composer selfupdate
  - composer install

script:
  - XDEBUG_MODE=coverage bin/phpunit  --coverage-clover coverage.xml --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)
