version: '3.3'
services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
    environment:
      - WEBROOT=/var/www/html/public/
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=host.docker.internal
