name: Integrate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.5
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, json
          #ini-values: pcov.directory=api #optional, see above for usage.
          coverage: pcov

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-interaction --no-suggest

      #- name: Setup PCOV
      #  run: |
      #    composer require pcov/clobber
      #    vendor/bin/pcov clobber

      - name: Run unittests
        run: XDEBUG_MODE=coverage bin/phpunit  --coverage-clover coverage.xml --coverage-text